package com.kenny.localmanager.ui

import androidx.compose.foundation.lazy.LazyListState
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import com.kenny.localmanager.file.DocumentFileModel
import com.kenny.localmanager.player.PlaybackState

internal data class DirectoryTabRouteState(
    val modifier: Modifier = Modifier,
    val currentUri: String,
    val refreshTrigger: Int,
    val dirCache: Map<String, CachedDir>,
    val onCacheDir: (uri: String, items: List<DocumentFileModel>) -> Unit,
    val pendingList: List<DocumentFileModel>,
    val rootUri: String?,
    val listState: LazyListState,
    val onNavigate: (String) -> Unit,
    val onBack: () -> Unit,
    val canGoBack: Boolean,
    val onEmptyTrash: (() -> Unit)? = null,
    val onRestoreFromTrash: ((DocumentFileModel) -> Unit)? = null,
    val isViewingTrash: Boolean = false,
    val filterVisible: Boolean = true,
    val hideDotFiles: Boolean = false,
    val preferredExternalPackages: Map<String, String> = emptyMap(),
    val onOpenFile: (uri: String, name: String, isEncrypted: Boolean) -> Unit,
    val onOpenWithOtherApp: (uri: String, name: String, packageName: String?, rememberChoice: Boolean) -> Boolean,
    val onClearExternalOpenPreference: (name: String) -> Unit,
    val onAddToPendingList: (DocumentFileModel) -> Unit,
    val onRemoveFromPendingList: (DocumentFileModel) -> Unit,
    val onCopyPendingToCurrentDir: () -> Unit,
    val onMovePendingToCurrentDir: () -> Unit,
    val onShowPendingList: (Boolean) -> Unit,
    val onRefresh: () -> Unit,
    val onChangeRoot: () -> Unit,
    val onCreateQuickNote: () -> Unit,
    val onShareFileToGit: ((DocumentFileModel) -> Unit)? = null,
    val onOpenMarkdownView: (uri: String, name: String, encrypted: Boolean) -> Unit,
    val onRequestGpgDecrypt: (DocumentFileModel, String) -> Unit,
    val onRequestGpgEncrypt: (DocumentFileModel, String) -> Unit,
    val onRequestQuickObfuscate: ((DocumentFileModel) -> Unit)? = null,
    val onRequestQuickDeobfuscate: ((DocumentFileModel) -> Unit)? = null,
    val onConfirmDelete: ((DocumentFileModel, Boolean) -> Unit)? = null,
    val onUnzipRequest: (DocumentFileModel) -> Unit,
    val onRequestMdZipView: (DocumentFileModel) -> Unit,
    val onRequestHtmlView: (DocumentFileModel) -> Unit,
    val onRequestHtmlZipView: (DocumentFileModel) -> Unit,
    val onRequestOpenUrl: (String) -> Unit,
    val onRequestLlmZipView: (DocumentFileModel) -> Unit,
    val onRequestEpubView: (DocumentFileModel) -> Unit,
    val onRequestPicZipView: (DocumentFileModel) -> Unit,
    val onRequestDirectoryImageView: (DocumentFileModel, String, List<DocumentFileModel>) -> Unit,
    val onRequestPdfView: (DocumentFileModel) -> Unit,
    val onCompressToZipRequest: (DocumentFileModel) -> Unit,
    val onCompressTo7zRequest: (DocumentFileModel) -> Unit,
    val onRequestPassProtect: ((DocumentFileModel) -> Unit)? = null,
    val onRequestPassView: (DocumentFileModel) -> Unit,
    val onRequestPassEdit: (DocumentFileModel, String) -> Unit,
    val onRequestTxtView: (DocumentFileModel) -> Unit,
    val onRequestLlmView: (DocumentFileModel) -> Unit,
    val onRequestImportConfig: ((DocumentFileModel) -> Unit)? = null,
    val onRequestImportStarDict: ((DocumentFileModel) -> Unit)? = null,
    val playbackState: PlaybackState? = null,
    val onOpenPlaybackScreen: () -> Unit
)

@Composable
internal fun DirectoryTabRoute(state: DirectoryTabRouteState) {
    FileBrowserScreen(
        modifier = state.modifier,
        currentUri = state.currentUri,
        refreshTrigger = state.refreshTrigger,
        dirCache = state.dirCache,
        onCacheDir = state.onCacheDir,
        pendingList = state.pendingList,
        rootUri = state.rootUri,
        listState = state.listState,
        onNavigate = state.onNavigate,
        onBack = state.onBack,
        canGoBack = state.canGoBack,
        onEmptyTrash = state.onEmptyTrash,
        onRestoreFromTrash = state.onRestoreFromTrash,
        isViewingTrash = state.isViewingTrash,
        filterVisible = state.filterVisible,
        hideDotFiles = state.hideDotFiles,
        preferredExternalPackages = state.preferredExternalPackages,
        onOpenFile = state.onOpenFile,
        onOpenWithOtherApp = state.onOpenWithOtherApp,
        onClearExternalOpenPreference = state.onClearExternalOpenPreference,
        onAddToPendingList = state.onAddToPendingList,
        onRemoveFromPendingList = state.onRemoveFromPendingList,
        onCopyPendingToCurrentDir = state.onCopyPendingToCurrentDir,
        onMovePendingToCurrentDir = state.onMovePendingToCurrentDir,
        onShowPendingList = state.onShowPendingList,
        onRefresh = state.onRefresh,
        onChangeRoot = state.onChangeRoot,
        onCreateQuickNote = state.onCreateQuickNote,
        onShareFileToGit = state.onShareFileToGit,
        onOpenMarkdownView = state.onOpenMarkdownView,
        onRequestGpgDecrypt = state.onRequestGpgDecrypt,
        onRequestGpgEncrypt = state.onRequestGpgEncrypt,
        onRequestQuickObfuscate = state.onRequestQuickObfuscate,
        onRequestQuickDeobfuscate = state.onRequestQuickDeobfuscate,
        onConfirmDelete = state.onConfirmDelete,
        onUnzipRequest = state.onUnzipRequest,
        onRequestMdZipView = state.onRequestMdZipView,
        onRequestHtmlView = state.onRequestHtmlView,
        onRequestHtmlZipView = state.onRequestHtmlZipView,
        onRequestOpenUrl = state.onRequestOpenUrl,
        onRequestLlmZipView = state.onRequestLlmZipView,
        onRequestEpubView = state.onRequestEpubView,
        onRequestPicZipView = state.onRequestPicZipView,
        onRequestDirectoryImageView = state.onRequestDirectoryImageView,
        onRequestPdfView = state.onRequestPdfView,
        onCompressToZipRequest = state.onCompressToZipRequest,
        onCompressTo7zRequest = state.onCompressTo7zRequest,
        onRequestPassProtect = state.onRequestPassProtect,
        onRequestPassView = state.onRequestPassView,
        onRequestPassEdit = state.onRequestPassEdit,
        onRequestTxtView = state.onRequestTxtView,
        onRequestLlmView = state.onRequestLlmView,
        onRequestImportConfig = state.onRequestImportConfig,
        onRequestImportStarDict = state.onRequestImportStarDict,
        playbackState = state.playbackState,
        onOpenPlaybackScreen = state.onOpenPlaybackScreen
    )
}
